inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/ParameterLists:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - x
    - y

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Enabled: false
